### ISSUE TITLE
Things todo for the paper writing

### ISSUE THREAD

**Issue by mojtaba-eshghie** [mojtaba-eshghie/solidity-code-diff#14]
- [ ] Unify the font sizes of all of the plots
- [ ] Fix the grey-scale problematic nature of the remaining two plots of the paper (should be at least somewhat similar to our histogram plot).

----
- [ ] Resolve the following thing

For the following, if the paper on GumTree provides support for that claim, it would be
good to cite it somewhere in the text with that context.
```
 BTW, we do not validate the edit scripts and trust the
> underlying Gumtree algorithm, which has been proven to provide at least
> correct edit scripts (even though not always the most optimized one).
```
